# Generated by Django 3.2.9 on 2021-11-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
    ]
