# Generated by Django 3.2.9 on 2021-12-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_name',
            field=models.ForeignKey(default='aa', on_delete=django.db.models.deletion.CASCADE, to='products.size_type', to_field='size_types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=200),
        ),
    ]
