# Generated by Django 3.2.9 on 2021-12-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_table_size_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_table',
            new_name='ProductTable',
        ),
        migrations.RenameModel(
            old_name='Size_type',
            new_name='SizeType',
        ),
    ]
