# Generated by Django 3.2.9 on 2021-12-05 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211205_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttable',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='producttable',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='producttable',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='producttable',
            name='image4',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='prd_img')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='prd_img')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='prd_img')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='prd_img')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='prd_img')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.producttable')),
            ],
        ),
    ]
