# Generated by Django 3.2.9 on 2021-12-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211205_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image5',
        ),
    ]
