# Generated by Django 3.2.9 on 2021-12-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
