# Generated by Django 3.2.9 on 2021-12-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalCoupen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupen_title', models.CharField(max_length=30)),
                ('coupen_code', models.CharField(max_length=30)),
                ('coupen_offer', models.FloatField()),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
