# Generated by Django 3.2.9 on 2021-12-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_normalcoupen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NormalCoupen',
            new_name='Coupen',
        ),
    ]
