# Generated by Django 3.2.9 on 2021-12-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_normalcoupen_coupen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupen',
            new_name='Coupon',
        ),
    ]
