# Generated by Django 3.2.9 on 2021-12-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_coupen_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='coupen_code',
            new_name='coupon_code',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='coupen_offer',
            new_name='coupon_offer',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='coupen_title',
            new_name='coupon_title',
        ),
    ]
