# Generated by Django 3.2.9 on 2021-12-17 05:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_favourite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'product')},
        ),
    ]
